server:
  port: 8080

email:
  user: 1966549568@qq.com
  code: qafcihztqchzeaha
  host: smtp.qq.com
  auth: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: root
